@startuml

left to right direction

title DFD: Регистрация пациента

actor Patient
actor Administrator
actor Doctor

rectangle "Расписание" as Timetable
rectangle "БД Пациентов" as PatientDB
rectangle "Файлы пациентов" as PatientFileStorage

Patient -> Administrator : Регистрация, Запись на прием, Передача файлов с данными
Administrator -> PatientDB : Сохранение данных пациента
Administrator -> Timetable : Запись на прием
Administrator -> PatientFileStorage : Сохранение файлов
Doctor -> PatientFileStorage : Доступ к файлам пациента
Doctor -> PatientDB : Получение данных пациента
Doctor -> Timetable : Просмотр расписания
@enduml
